version: 1.0.{build}
image: Visual Studio 2017

install:
  - cmd: dotnet --info
  - cmd: dotnet restore src

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  verbosity: minimal

test_script:
  - dotnet test src/SJP.ProcessRedux.Tests/SJP.ProcessRedux.Tests.csproj --configuration Release --logger:trx;LogFileName=SJP.ProcessRedux.Tests.results.xml
  - ps: build/uploadtests.ps1 "src/SJP.ProcessRedux.Tests/TestResults/SJP.ProcessRedux.Tests.results.xml"

notifications:
- provider: Email
  to:
    - simon@sjp.co.nz
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
